CREATE TABLE IF NOT EXISTS Person(
    PhoneID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(30) NOT NULL,
    surname VARCHAR(30),
    patronumic VARCHAR (30),
    photo VARCHAR (150),
    description VARCHAR(150),
    dateOfBirth DATE
)
;

CREATE TABLE IF NOT EXISTS Mark(
    MarkID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    type    VARCHAR(20) UNIQUE
)
;

CREATE TABLE IF NOT EXISTS MarkSet(
    MarkSetID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    MarkID  INTEGER NULL,
    PersonID    INTEGER NULL,

        FOREIGN KEY (PersonID)
        REFERENCES Person(PersonID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

        FOREIGN KEY (MarkID)
        REFERENCES Mark(MarkID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
)
;

CREATE TABLE IF NOT EXISTS Phone(
    PhoneID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    PersonID INTEGER NULL,
    number CHAR(11),

        FOREIGN KEY (PersonID)
        REFERENCES Person(PersonID)
        ON DELETE SET DEFAULT
        ON UPDATE CASCADE
)
;

CREATE TABLE IF NOT EXISTS CallDetails(
    CallDEtailsID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    PhoneID INTEGER NOT NULL,
    dateOfCall DATETIME,
    duration INTEGER,
    STATUS VARCHAR(30),
        FOREIGN KEY (PhoneID)
        REFERENCES Phone(PhoneID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
)
;
